object GeminiAIFrame_Setting: TGeminiAIFrame_Setting
  Left = 0
  Top = 0
  Width = 1024
  Height = 668
  Margins.Left = 7
  Margins.Top = 7
  Margins.Right = 7
  Margins.Bottom = 7
  Align = alClient
  Color = clWindow
  ParentBackground = False
  ParentColor = False
  TabOrder = 0
  PixelsPerInch = 216
  object Chk_Enabled: TCheckBox
    AlignWithMargins = True
    Left = 11
    Top = 23
    Width = 1006
    Height = 36
    Margins.Left = 11
    Margins.Top = 23
    Margins.Right = 7
    Margins.Bottom = 7
    Align = alTop
    Caption = 'Enabled'
    TabOrder = 0
  end
  object Edt_ApiKey: TLabeledEdit
    AlignWithMargins = True
    Left = 52
    Top = 194
    Width = 949
    Height = 45
    Margins.Left = 52
    Margins.Top = 38
    Margins.Right = 23
    Margins.Bottom = 7
    Align = alTop
    EditLabel.Width = 87
    EditLabel.Height = 37
    EditLabel.Margins.Left = 7
    EditLabel.Margins.Top = 7
    EditLabel.Margins.Right = 7
    EditLabel.Margins.Bottom = 7
    EditLabel.Caption = 'Api key'
    LabelSpacing = 4
    PasswordChar = '*'
    TabOrder = 2
    Text = ''
  end
  object Edt_BaseURL: TLabeledEdit
    AlignWithMargins = True
    Left = 52
    Top = 104
    Width = 949
    Height = 45
    Margins.Left = 52
    Margins.Top = 38
    Margins.Right = 23
    Margins.Bottom = 7
    Align = alTop
    EditLabel.Width = 102
    EditLabel.Height = 37
    EditLabel.Margins.Left = 7
    EditLabel.Margins.Top = 7
    EditLabel.Margins.Right = 7
    EditLabel.Margins.Bottom = 7
    EditLabel.Caption = 'BaseURL'
    LabelSpacing = 4
    TabOrder = 1
    Text = ''
  end
  object Edt_Model: TLabeledEdit
    AlignWithMargins = True
    Left = 52
    Top = 284
    Width = 949
    Height = 45
    Margins.Left = 52
    Margins.Top = 38
    Margins.Right = 23
    Margins.Bottom = 7
    Align = alTop
    EditLabel.Width = 77
    EditLabel.Height = 37
    EditLabel.Margins.Left = 7
    EditLabel.Margins.Top = 7
    EditLabel.Margins.Right = 7
    EditLabel.Margins.Bottom = 7
    EditLabel.Caption = 'Model'
    LabelSpacing = 4
    TabOrder = 3
    Text = ''
  end
  object Edt_Timeout: TLabeledEdit
    AlignWithMargins = True
    Left = 52
    Top = 374
    Width = 949
    Height = 45
    Margins.Left = 52
    Margins.Top = 38
    Margins.Right = 23
    Margins.Bottom = 7
    Align = alTop
    EditLabel.Width = 148
    EditLabel.Height = 37
    EditLabel.Margins.Left = 7
    EditLabel.Margins.Top = 7
    EditLabel.Margins.Right = 7
    EditLabel.Margins.Bottom = 7
    EditLabel.Caption = 'Timeout(ms)'
    LabelSpacing = 4
    TabOrder = 4
    Text = '30000'
  end
end
